source "https://rubygems.org"

ruby "3.4.8"

gem "base64"
gem "loofah", "~> 2.24"
gem "nokogiri", "~> 1.18"
gem "puma", "~> 6.6"
gem "rack", "~> 3.2"
gem "rackup", "~> 2.2"
gem "rails-html-sanitizer", "~> 1.6"
